
package ch.fhnw.wi.eai.bankjd;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankJD", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankJD {


    /**
     * 
     * @param nachname
     * @param adresse
     * @param vorname
     * @param kontostand
     * @param queryNachname
     * @param land
     * @param bic
     * @param ranking
     * @param ibanKontonummer
     * @param queryVorname
     */
    @WebMethod
    @RequestWrapper(localName = "holeKontoKorrent", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.HoleKontoKorrent")
    @ResponseWrapper(localName = "holeKontoKorrentResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.HoleKontoKorrentResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/holeKontoKorrentRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/holeKontoKorrentResponse")
    public void holeKontoKorrent(
        @WebParam(name = "queryVorname", targetNamespace = "")
        String queryVorname,
        @WebParam(name = "queryNachname", targetNamespace = "")
        String queryNachname,
        @WebParam(name = "vorname", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> vorname,
        @WebParam(name = "nachname", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> nachname,
        @WebParam(name = "adresse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> adresse,
        @WebParam(name = "land", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> land,
        @WebParam(name = "ranking", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> ranking,
        @WebParam(name = "ibanKontonummer", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ibanKontonummer,
        @WebParam(name = "kontostand", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Float> kontostand,
        @WebParam(name = "bic", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> bic);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printKontokorrent", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.PrintKontokorrent")
    @ResponseWrapper(localName = "printKontokorrentResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.PrintKontokorrentResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/printKontokorrentRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/printKontokorrentResponse")
    public void printKontokorrent();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printSparkonto", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.PrintSparkonto")
    @ResponseWrapper(localName = "printSparkontoResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.PrintSparkontoResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/printSparkontoRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/printSparkontoResponse")
    public void printSparkonto();

    /**
     * 
     * @param zinsen
     * @param nachname
     * @param strasse
     * @param vorname
     * @param kontostand
     * @param plzOrt
     * @param queryNachname
     * @param kontonummer
     * @param queryVorname
     */
    @WebMethod
    @RequestWrapper(localName = "holeSparkonto", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.HoleSparkonto")
    @ResponseWrapper(localName = "holeSparkontoResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.HoleSparkontoResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/holeSparkontoRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/holeSparkontoResponse")
    public void holeSparkonto(
        @WebParam(name = "queryVorname", targetNamespace = "")
        String queryVorname,
        @WebParam(name = "queryNachname", targetNamespace = "")
        String queryNachname,
        @WebParam(name = "vorname", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> vorname,
        @WebParam(name = "nachname", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> nachname,
        @WebParam(name = "strasse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> strasse,
        @WebParam(name = "plzOrt", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> plzOrt,
        @WebParam(name = "zinsen", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Float> zinsen,
        @WebParam(name = "kontonummer", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Long> kontonummer,
        @WebParam(name = "kontostand", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Long> kontostand);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeKontokorrentNachname", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.ListeKontokorrentNachname")
    @ResponseWrapper(localName = "listeKontokorrentNachnameResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.ListeKontokorrentNachnameResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/listeKontokorrentNachnameRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/listeKontokorrentNachnameResponse")
    public List<String> listeKontokorrentNachname();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeSparkontoNachname", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.ListeSparkontoNachname")
    @ResponseWrapper(localName = "listeSparkontoNachnameResponse", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", className = "ch.fhnw.wi.eai.bankjd.ListeSparkontoNachnameResponse")
    @Action(input = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/listeSparkontoNachnameRequest", output = "http://www.fhnw.ch/wi/eai/bankjd/BankJD/listeSparkontoNachnameResponse")
    public List<String> listeSparkontoNachname();

}
