
package ch.fhnw.wi.eai.bankjd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankJDService", targetNamespace = "http://www.fhnw.ch/wi/eai/bankjd/", wsdlLocation = "http://localhost:8080/BankJDService?wsdl")
public class BankJDService
    extends Service
{

    private final static URL BANKJDSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKJDSERVICE_EXCEPTION;
    private final static QName BANKJDSERVICE_QNAME = new QName("http://www.fhnw.ch/wi/eai/bankjd/", "BankJDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BankJDService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKJDSERVICE_WSDL_LOCATION = url;
        BANKJDSERVICE_EXCEPTION = e;
    }

    public BankJDService() {
        super(__getWsdlLocation(), BANKJDSERVICE_QNAME);
    }
    
    public BankJDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKJDSERVICE_QNAME, features);
    }

    public BankJDService(URL wsdlLocation) {
        super(wsdlLocation, BANKJDSERVICE_QNAME);
    }

    public BankJDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKJDSERVICE_QNAME, features);
    }

    public BankJDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankJDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankJD
     */
    @WebEndpoint(name = "BankJDPort")
    public BankJD getBankJDPort() {
        return super.getPort(new QName("http://www.fhnw.ch/wi/eai/bankjd/", "BankJDPort"), BankJD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankJD
     */
    @WebEndpoint(name = "BankJDPort")
    public BankJD getBankJDPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fhnw.ch/wi/eai/bankjd/", "BankJDPort"), BankJD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKJDSERVICE_EXCEPTION!= null) {
            throw BANKJDSERVICE_EXCEPTION;
        }
        return BANKJDSERVICE_WSDL_LOCATION;
    }

}
